### ISSUE TITLE
Compile fails on latest ubuntu

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/GhostsNGoblinsDS#1]
demetris@demetris-TA770E3:~/Desktop/Development/GhostsNGoblinsDS$ git diff
diff --git a/source/FileHandling.c b/source/FileHandling.c
index 73fa0ff..7ccfcad 100644
--- a/source/FileHandling.c
+++ b/source/FileHandling.c
@@ -10,7 +10,7 @@
 #include "FileHandling.h"
 #include "Shared/EmuMenu.h"
 #include "Shared/FileHelper.h"
-#include "Shared/unzip/unzipnds.h"
+#include "Shared/Unzip/unzipnds.h"
 #include "Shared/EmubaseAC.h"
 #include "Main.h"
 #include "Gui.h"
diff --git a/source/Gui.c b/source/Gui.c
index 5fab871..10b4069 100644
--- a/source/Gui.c
+++ b/source/Gui.c
@@ -11,7 +11,7 @@
 #include "io.h"
 #include "ARM6809/Version.h"
 #include "ARMZ80/Version.h"
-#include "GngVideo/Version.h"
+#include "GnGVideo/Version.h"
 
 #define EMUVERSION "V0.1.6 2022-04-11"
I had to add these to fix compile but after this i got

linking GhostsNGoblinsDS.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHandling.o: in function `loadRoms':
/home/demetris/Desktop/Development/GhostsNGoblinsDS/source/FileHandling.c:246: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/FileHandling.c:248: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/FileHandling.c:256: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/FileHandling.c:258: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHelper.o: in function `loadROM':
/home/demetris/Desktop/Development/GhostsNGoblinsDS/source/Shared/FileHelper.c:69: undefined reference to `loadFileTypeInZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/Shared/FileHelper.c:91: undefined reference to `cenHead'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/Shared/FileHelper.c:91: undefined reference to `zipFilename'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/GhostsNGoblinsDS/source/Shared/FileHelper.c:91: undefined reference to `zipError'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /home/demetris/Desktop/Development/GhostsNGoblinsDS/GhostsNGoblinsDS.elf] Error 1
make: *** [Makefile:121: build] Error 2

**Comment by FluBBaOfWard** [comment]
The makefile had a path to unzip as well, can you see if my changes fix the problems.

**Comment by Ntemis** [comment]
Good job compiled fine, closing down
